---
title: "Draft MRA Report"
author: "Madeline Scott"
date: "12/9/2020"
output: html_document
---

```{r set-options, eval = TRUE, echo = FALSE, include = FALSE}
options(width = 150)

library(tidyverse)
library(dplyr)
library(tibble)
library(magrittr)
library(knitr)
library(kableExtra)
library(rjson)
library(jsonlite)
library(broom)
library(data.table)
library(xtable)
library(gridExtra)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(GGally)
library(grid)
library(olsrr)
library(fBasics)
library(car)
library(purrr)
```

```{r eval = TRUE, echo = FALSE}
#Read NCSS sales list in JSON format
AllSalesJSON <- fromJSON("Area72NCSSData.json", flatten = TRUE)

AllSales <- as.data.frame(AllSalesJSON)

#Filter out RemBefore
AllSales_RemBefore <- AllSales %>%
  dplyr::filter(AllSales$RemBefore == "0")

#Filter out RemDuring
GoodSales <- AllSales_RemBefore %>%
  dplyr::filter(AllSales_RemBefore$RemDuring == "0")

#create table with only necessary columns - independend variable and chosen dependent variables
necessary_data <- GoodSales %>%
  select(LnTrendedPrice, BaseLandC, ConditionC, GradeC, TotalRcnC, KingCountyYN,
         Plat320493YN, Plat736630YN, Plats29440X, Plats76952X,
         Sub8YN, Nghb11_12_YN, AgeC_Ren_Cubed)

#Descriptive Statistics
#Create standard error function
std <- function(x) sd(x)/sqrt(length(x))

#Display descriptive statistics of model
descriptive_stats <- data.table("Variable" = c(colnames(necessary_data)))
descriptive_stats$Count <- count(necessary_data)
descriptive_stats$Mean <- apply(necessary_data, 2, mean)
descriptive_stats$Standard.Deviation <- apply(necessary_data, 2, std)
descriptive_stats$Min <- apply(necessary_data, 2, min)
descriptive_stats$Max <- apply(necessary_data, 2, max)

descriptive_stats_final <- descriptive_stats %>% rename("Std. Dev." = "Standard.Deviation")
```

## Descriptive Statistics

```{r eval = TRUE, echo = FALSE, results="asis"}
kbl(descriptive_stats_final, digits = 5) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left")
```
```{r eval = TRUE, echo = FALSE}
#Create variables for computing the multiple regression processes
response_var <-necessary_data[,1]
regressor1 <- necessary_data[,2]
regressor2 <- necessary_data[,3]
regressor3 <- necessary_data[,4]
regressor4 <- necessary_data[,5]
regressor5 <- necessary_data[,6]
regressor6 <- necessary_data[,7]
regressor7 <- necessary_data[,8]
regressor8 <- necessary_data[,9]
regressor9 <- necessary_data[,10]
regressor10 <- necessary_data[,11]
regressor11 <- necessary_data[,12]
regressor12 <- necessary_data[,13]

#Create table of IV from necessary_data
IV_table <- necessary_data[,-1]

#Create a list of IV
regressors <- ls(pat = "regressor")

#Apply multiple regression
model <- lm(response_var ~ regressor1 + regressor2 + regressor3 +
              regressor4 + regressor5 + regressor6 + regressor7 + regressor8 +
              regressor9 + regressor10 + regressor11 + regressor12)

#Show Estimated equation
model_equation <- function(model, ...) {
  format_args <- list(...)
  
  model_coeff <- model$coefficients
  format_args$x <- abs(model$coefficients)
  model_coeff_sign <- sign(model_coeff)
  model_coeff_prefix <- case_when(model_coeff_sign == -1 ~ " - ",
                                  model_coeff_sign == 1 ~ " + ",
                                  model_coeff_sign == 0 ~ " + ")
  model_eqn <- paste(strsplit(as.character(colnames(necessary_data)), "~")[[1]], # 'y'
                     "=",
                     paste(if_else(model_coeff[1]<0, "- ", ""),
                           do.call(format, format_args)[1],
                           paste(model_coeff_prefix[-1],
                                 do.call(format, format_args)[-1],
                                 " * ",
                                 names(necessary_data[-1]),
                                 sep = "", collapse = ""),
                           sep = ""))
  return(model_eqn)}
```
## Estimated Equation

```{r eval = TRUE, echo = FALSE}
print(model_equation(model)) #Returns estimated equation in the usual form
```


## Correlation Matrix

```{r eval = TRUE, echo = FALSE}
#Correlation Matrix
corr_matrix <-correlation_matrix <- ggcorr(necessary_data, label = TRUE, layout.exp = 1, nbreaks = 5, palette = "RdBu", label_round = 2, label_size = 3, size = 0)
corr_names <- data.frame(x=seq(necessary_data), y=seq(necessary_data), lbs = names(necessary_data))
corr_matrix + geom_text(data=corr_names, aes(x, y, label = names(necessary_data), hjust = .3), size = 2.5)
```

## Regression Coefficients T-Tests

```{r eval= TRUE, echo = FALSE}
#Regression Coefficients T-Tests
coefficient <- as.data.frame(summary(model)$coefficient, row.names = FALSE)

coefficient$Variables <- c(colnames(necessary_data)) # adding actual variable names
coefficient$Reject <- "Yes" #Adding a 'Reject H0 at 1%?' column
coefficient$Reject[coefficient$'Pr(>|t|)' > 0.05] <- "No"

## Needs Fixing t.test(necessary_data$LnTrendedPrice, necessary_data$BaseLandC)

coefficient_final <- coefficient[,c(5, 1, 2, 3, 4, 6)] %>% rename("Regression Coefficient" = "Estimate",
                       "T-Statistic to Test H0" = "t value",
                       "Prob Level" = "Pr(>|t|)",
                       "Reject H0 at 5%?" = "Reject")
```

```{r eval = TRUE, echo = FALSE, results="asis"}
kbl(coefficient_final, digits = 8) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left")
```
# Regression Coefficients Confidence Intervals

```{r eval = TRUE, echo = FALSE}
conf_limits <- as.data.frame(confint(model, level = 0.95)) %>%
  rename("Lower 95% Conf. Limit" = "2.5 %",
         "Upper 95% Conf. Limit" = "97.5 %")

conf_limits$Regression.Coefficient <- coefficient[1]
conf_limits$Standard.Error <- coefficient[2]
conf_limits$Variable <- colnames(necessary_data)

full_conf_limits <- conf_limits[, c(5,3, 4, 1, 2)] %>%
  rename("Std. Error" = "Standard.Error",
         "Regression Coefficient" = "Regression.Coefficient")
rownames(full_conf_limits) <- c()
```

```{r eval = TRUE, echo = FALSE, results= "asis"}
kbl(full_conf_limits, digits = 5) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left")
```

## Analysis of Variance Detail (ANOVA)
```{r eval = TRUE, echo = FALSE}
#Analysis of variance detail ANOVA
variance_detail <- as.data.table(anova(model)) %>%
  rename("Sum of Squares" = "Sum Sq",
         "Prob Level" = "Pr(>F)")

variance_detail$Variables <- c(colnames(IV_table), "Error")

anova_final <- variance_detail[,c(6,1, 2, 3, 4, 5)]
  
kbl(anova_final, digits = 5) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left")
```

## Normality of Residuals  

```{r eval = TRUE, echo = FALSE, message = FALSE, fig.width = 9}
#Plot: histogram of residuals of LnTrendedPrice
hist_residual <- qplot(resid(model),
                       geom = "histogram",
                       bins = 20,
                       col = I("black"),
                       fill = I("yellow")) +
  labs(title = "Histogram of Residuals",
       x = "Residual",
       y = "Frequency")

#Plot: probability plot
prob_plot <- ggplot(data = GoodSales, aes(sample = resid(model))) +
  geom_qq() +
  geom_qq_line(color = "red") +
  labs(title = "Probability Plot of Residuals",
       x = "Theoretical Quantiles",
       y = "Residuals")

normality_plots <-grid.arrange(hist_residual, prob_plot, ncol = 2)
```

```{r eval = TRUE, echo = FALSE, include=FALSE}
return(normality_plots)
```


```{r eval = TRUE, echo = FALSE, results='asis'}
shapiro_table <- as.data.table(shapiroTest(resid(model))@test)
anderson_table <- as.data.table(adTest(resid(model))@test)
dagostino_table <-as.data.table(dagoTest(resid(model))@test)

normality_output <- rbind(shapiro_table, anderson_table, dagostino_table)[,-4] %>%
  rename("Test Name" = "method",
         "Prob Level" = "p.value",
         "Test Statistic" = "statistic")
normality_output <- normality_output[, c(3,1,2)]


kbl(normality_output, digits = 5) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "left")
```


## Residual of Y vs Sale Price

```{r eval = TRUE, echo = FALSE}
plot(GoodSales$Sprice, resid(model),
     main = "" ,
     xlab = "Sale Price" ,
     ylab = "Residual of Y")
abline(h = 0, col = "red")
```

# Variable Plots  

## Fitted Y vs Fitted X

```{r eval = TRUE, echo = FALSE}
#set number of rows based on number of IVs
graphs_layout_rows <- ceiling(length(regressors)/2)
marginalModelPlots(model = model, main="", ylab = "LnTrendedPrice", smooth = FALSE, ask = FALSE, col = "blue")
```


## Partial Residual Plots

```{r eval = TRUE, echo = FALSE}
crPlots((model = model), ask = FALSE, ylab = "Resid. LnTrendedPrice", col = "red", smooth = FALSE)
```


